[ATB-217] Reduce cognitive complexity in checkYourPhoneService method
alphagov/di-account-management-frontend pull request #803
Opened 2023-02-07 09:58 UTC by chiarapascucci-gds

## Proposed changes
Currently the checkYourPhoneService Interface describes an async function that takes in 8 parameters. This is flagged as a code smell as the cognitive complexity is too high (max number of parameters is 7). This PR changes the interface definition so that the method signature only requires 2 parameters

### What changed
The CheckYourPhoneServiceInterface was updated so to take 2 objects as its parameters. Those objects represent the user's input (email, updated info, and otp code) and session details respectively. The way this information is accessed when forming the post request to the relevant API was also changed in line with this restructuring

### Why did it change
Aim is to reduce cognitive complexity of the method

### Issue tracking
- [ATB-217](https://govukverify.atlassian.net/jira/software/c/projects/ATB/boards/241?modal=detail&selectedIssue=ATB-217)

### Testing
Changes were tested during development

## Local
Tested the changes locally (in Docker container) through existing unit and integration tests. All passed
![Screenshot 2023-02-06 at 12 22 34](https://user-images.githubusercontent.com/110468890/217207602-14c0320f-4481-494d-80bb-f6a22f3decaa.png)

![Screenshot 2023-02-06 at 12 20 24](https://user-images.githubusercontent.com/110468890/217207633-be8af1f3-8e48-4dc9-8322-b093090d1d6c.png)

## Deployed
Deployed a new version of the application to the AWS dev environment successfully and manually tested account creation, changing password, account deletion, log in/out. Message received on mobile phone when adding phone number

## Checklists

### Environment variables or secrets
- [x] No environment variables or secrets were added or changed

### Other considerations
- [ ] Demo to a BA, TA, and the team.
- [ ] Recorded demo shared on [#govuk-accounts-tech](https://gds.slack.com/archives/C011Y5SAY3U)
- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2023-02-07 10:44 UTC, TaherKapasi commented
Hi @chiarapascucci-gds - could you exclude  the changes from src/assets/javascript/cookies.js please and rebase into single commit please - thanks

2023-02-07 10:44 UTC, TaherKapasi requested changes

2023-02-07 10:44 UTC, TaherKapasi commented on src/components/check-your-phone/check-your-phone-controller.ts
> +import {UpdateInformationInput, UpdateInformationSessionValues} from "../../utils/types";
```suggestion
import { UpdateInformationInput, UpdateInformationSessionValues } from "../../utils/types";
```

2023-02-07 10:44 UTC, TaherKapasi commented on src/components/check-your-phone/check-your-phone-controller.ts
> +
remove spare line

2023-02-07 10:44 UTC, TaherKapasi commented on src/components/check-your-phone/check-your-phone-service.ts
> +import {UpdateInformationInput, UpdateInformationSessionValues} from "../../utils/types";
```suggestion
import { UpdateInformationInput, UpdateInformationSessionValues } from "../../utils/types";
```

2023-02-07 10:44 UTC, TaherKapasi commented on src/components/check-your-phone/tests/check-your-phone-service.test.ts
> +import {UpdateInformationInput, UpdateInformationSessionValues} from "../../../utils/types";
```suggestion
import { UpdateInformationInput, UpdateInformationSessionValues } from "../../../utils/types";
```

2023-02-07 10:44 UTC, TaherKapasi commented on src/components/check-your-phone/types.ts
> +import {UpdateInformationInput, UpdateInformationSessionValues} from "../../utils/types";
```suggestion
import { UpdateInformationInput, UpdateInformationSessionValues } from "../../utils/types";
```

2023-02-07 11:14 UTC, KG700 commented on src/components/check-your-phone/check-your-phone-controller.ts
> +    const updateInput : UpdateInformationInput= {
```suggestion
    const updateInput : UpdateInformationInput = {
```

2023-02-07 14:40 UTC, chiarapascucci-gds reviewed
ok

2023-02-08 10:31 UTC, TaherKapasi submitted a review, later dismissed

2023-02-08 13:16 UTC, KG700 commented on src/components/check-your-phone/check-your-phone-service.ts
>        )
Remove the extra whitespace on lines 10 & 21-26.

2023-02-08 15:05 UTC, KG700 approved these changes

2023-02-09 13:24 UTC, TaherKapasi approved these changes

2023-02-09 16:31 UTC, huwd approved these changes

2023-02-13 13:34 UTC, merged